
# ***************************************************************************************************************************************
# * docker-compose-redis.yml                                                                                                            *
#  **************************************************************************************************************************************
#  *                                                                                                                                    *
#  * @License Starts                                                                                                                    *
#  *                                                                                                                                    *
#  * Copyright © 2024. MongoExpUser.  All Rights Reserved.                                                                              *
#  *                                                                                                                                    *
#  * License: MIT - https://github.com/MongoExpUser/DynamoDB-Local-and-Hybrid-Web-Application-Server/blob/main/LICENSE                  *
#  *                                                                                                                                    *
#  * @License Ends                                                                                                                      *
#  **************************************************************************************************************************************
# *                                                                                                                                     *
# *  Project: DynamoDB-Local and Hybrid Web-Application Server                                                                          *
# *                                                                                                                                     *
# *  This docker compose file deploys:                                                                                                  *
# *                                                                                                                                     *                                                                                                              *
# *     1)  DynamoDB-Local Datastore Node                                                                                               *
# *                                                                                                                                     *
# *     2)  Hybrid Web-Application Server Node, which includes:                                                                         *
# *         a) Simple Vanilla NodeJS HTTP Server, and                                                                                   *
# *         b) Application via Node.js or Python or AWS CLI                                                                             *
# *                                                                                                                                     *
# *                                                                                                                                     *
# *  Image names:                                                                                                                       *
# *  - amazon/dynamodb-local:latest and                                                                                                 *
# *  - hybridserver/ubuntu-22.04-nodejs-21-python-3.11-aws-cli-2:latest                                                                 *
# *                                                                                                                                     *
# *  Purpose: Run DynamoDB-Local Datastore and Hybrid Web-Application Server in Containers                                              *
# *                                                                                                                                     *
# ***************************************************************************************************************************************


services:
  dynamodb-node:
    image: amazon/dynamodb-local:latest
    command:  -jar DynamoDBLocal.jar -sharedDb -dbPath ./data && sudo tail -f /dev/null"
    container_name: dynamodb-node
    restart: always
    ports:
      - 8000:8000
    extra_hosts:
      - host.docker.internal:host-gateway
    volumes:
      - ./docker/dynamodb:/home/dynamodblocal/data
    working_dir: /home/dynamodblocal
    healthcheck:
      test: ["CMD-SHELL", "ls -lh /home/dynamodblocal"]
      interval: 6s
      timeout: 3s
      retries: 3
  webappserver-node:
    depends_on:
      - dynamodb-node
    image: server/ubuntu-22.04-nodejs-21-python-3.11:latest
    environment:
      KEY: ${AWS_ACCESS_KEY_ID}
      SECRET: ${AWS_SECRET_ACCESS_KEY}
      REGION: ${AWS_REGION}
    command: >
      bash -c "sudo sleep 10 
      && set PWD=%cd%
      && sudo aws configure set aws_access_key_id $${KEY} --profile default
      && sudo aws configure set aws_secret_access_key $${SECRET} --profile default
      && sudo aws configure set aws_region $${REGION} --profile default
      && echo ''
      && echo '------- Testing DynamoDB AWS CLI on the Server ----------- starts'
      && echo '---------------- Describe Limits -------------------------'
      && sudo aws dynamodb describe-limits --endpoint-url http://dynamodb-node:8000 --region $${REGION} --profile default
      && echo '---------------- Create Table ----------------------------'
      && sudo aws dynamodb create-table --table-name carsale --attribute-definitions AttributeName=manufacturer,AttributeType=S AttributeName=model,AttributeType=S --key-schema AttributeName=manufacturer,KeyType=HASH AttributeName=model,KeyType=RANGE --billing-mode PAY_PER_REQUEST --endpoint-url http://dynamodb-node:8000 --region $${REGION} --profile default
      && echo '---------------- List Table ------------------------------'
      && sudo aws dynamodb list-tables --endpoint-url http://dynamodb-node:8000 --region $${REGION} --profile default
      && echo '------- Testing DynamoDB AWS CLI on the Server ----------- ends'
      && echo ''
      && echo '---------------- Start Web Server ------------------------'
      && sudo node --max-old-space-size=4096 --inspect=9250 --no-warnings --trace-deprecation --watch --experimental-default-type=commonjs --experimental-websocket /home/base/web/app.js
      && echo ''
      && sudo tail -f /dev/null
      "
    container_name: webappserver-node
    restart: always
    ports:
      - 80:80
    extra_hosts:
      - host.docker.internal:host-gateway
    volumes:
      - ./web:/home/base/web
      - ./app:/home/base/app
      - webapplog:/var/log
    healthcheck:
      test: ["CMD-SHELL", "sudo ls -lhs /home/base/web && sudo ls -lhs /home/base/app"]
      interval: 6s
      timeout: 3s
      retries: 3
volumes:
  webapplog:
